version: 0.0
os: linux
files:
  - source: build/
    destination: /var/www/html/

file_exists_behavior: OVERWRITE

Hooks:
  - BeforeInstall: scripts/before_install.sh
  - AfterInstall: scripts/after_install.sh